version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  allow:
    - dependency-name: "*dss-deploy-scripts*"
  open-pull-requests-limit: 10
  reviewers:
    - "ethanbennett"
  target-branch: "dai.js"
