version: 2
jobs:
  build:
    docker:
      - image: levity/dapptools-node-latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn
            yarn install-nix
      - run:
          name: Build new snapshot
          command: |
            source /home/circleci/setup-env.sh
            yarn deploy-mcd
            yarn create-default-snapshot
            git config user.email "ebennett19@gmail.com"
            git config user.name "Ethan Bennett"
            git add .
            git commit -m "Create new snapshot"

# Add git push
# See about removing personal details from file
# Should only run on PR