# WIP

version: 2
filters:
  branches:
    only:
      - update-dss-deploy-scripts
      - circleci-config
jobs:
  build:
    docker:
      - image: levity/dapptools-node-latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn
            yarn install-nix
      - run:
          name: Build new snapshot
          command: |
            source /home/circleci/setup-env.sh
            yarn deploy-mcd:ci
            yarn create-default-snapshot
            git config user.email "ebennett19@gmail.com"
            git config user.name "Ethan Bennett"
            git add .
            git commit -m "Create new snapshot"

# git/yarn authentication:
  # should move out of this file
  # should allow for pushing to this branch
  # should allow for publishing